packages:
  - apps/*
  - packages/*

catalog:
  '@lingui/cli': ^5.4.1
  '@lingui/core': ^5.4.1
  '@lingui/loader': ^5.4.1
  '@lingui/react': ^5.4.1
  '@lingui/swc-plugin': 5.5.2
  '@orpc/client': ^1.8.2
  '@orpc/server': ^1.8.2
  '@orpc/tanstack-query': ^1.8.2
  '@types/node': ^24.3.0
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  better-auth: ^1.3.7
  next: ^15.5.0
  react: ^19.1.1
  react-dom: ^19.1.1
  tsdown: ^0.14.1
  typescript: ^5.9.2
  zod: ^4.0.17

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
