packages:
  - 'apps/*'
  - 'packages/*'
onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - '@tailwindcss/oxide'
  - 'unrs-resolver'

catalog:
  zod: ^4.0.5
  tsdown: ^0.12.9
  typescript: ^5.8.3
  '@types/node': ^24.0.14
  '@orpc/server': ^1.7.1
  '@orpc/client': ^1.7.1
  '@orpc/tanstack-query': ^1.7.1
  '@lingui/core': ^5.3.3
  '@lingui/react': ^5.3.3
  '@lingui/cli': ^5.3.3
  '@lingui/loader': ^5.3.3
  '@lingui/swc-plugin': ^5.5.2
