packages:
  - apps/*
  - packages/*

catalog:
  '@lingui/cli': ^5.4.0
  '@lingui/core': ^5.4.0
  '@lingui/loader': ^5.4.0
  '@lingui/react': ^5.4.0
  '@lingui/swc-plugin': 5.5.2
  '@orpc/client': ^1.7.11
  '@orpc/server': ^1.7.11
  '@orpc/tanstack-query': ^1.7.11
  '@types/node': ^24.1.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  better-auth: ^1.3.4
  next: ^15.4.6
  react: ^19.1.1
  react-dom: ^19.1.1
  tsdown: ^0.14.0
  typescript: ^5.9.2
  zod: ^4.0.17

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
