packages:
  - apps/*
  - packages/*

catalog:
  '@lingui/cli': ^5.3.3
  '@lingui/core': ^5.3.3
  '@lingui/loader': ^5.3.3
  '@lingui/react': ^5.3.3
  '@lingui/swc-plugin': 5.5.2
  '@orpc/client': ^1.7.4
  '@orpc/server': ^1.7.4
  '@orpc/tanstack-query': ^1.7.4
  '@types/node': ^24.1.0
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  better-auth: ^1.3.3
  next: ^15.4.3
  react: ^19.1.0
  react-dom: ^19.1.0
  tsdown: ^0.13.0
  typescript: ^5.8.3
  zod: ^4.0.8

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
