packages:
  - apps/*
  - packages/*

catalog:
  '@lingui/cli': ^5.4.1
  '@lingui/core': ^5.4.1
  '@lingui/loader': ^5.4.1
  '@lingui/react': ^5.4.1
  '@lingui/swc-plugin': 5.5.2
  '@orpc/client': ^1.8.6
  '@orpc/server': ^1.8.6
  '@orpc/tanstack-query': ^1.8.6
  '@types/node': ^24.3.1
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  better-auth: ^1.3.8
  next: ^15.5.2
  react: ^19.1.1
  react-dom: ^19.1.1
  tsdown: ^0.14.2
  typescript: ^5.9.2
  zod: ^4.1.5

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
