import { Providers } from '../providers'
import './styles/index.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  appleWebApp: {
    title: 'Starter Next App',
  },
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '96x96',
      url: '/favicon-96x96.png',
    },
    {
      rel: 'icon',
      type: 'image/svg+xml',
      url: '/favicon.svg',
    },
    {
      rel: 'shortcut icon',
      url: '/favicon.ico',
    },
    {
      rel: 'app-touch-icon',
      sizes: '180x180',
      url: '/apple-touch-icon.png',
    },
  ],
}

export function getRootLayout(lang: string) {
  function RootLayout({ children }: { children: ReactNode }) {
    return (
      <html lang={lang} suppressHydrationWarning>
        <body>
          <Providers lang={lang}>{children}</Providers>
        </body>
      </html>
    )
  }
  return RootLayout
}
