import { linguiConfig } from '~/i18n/config'
import { Providers } from '~/providers'
import type { SupportedLocale } from '@workspace/shared'
import type { Metadata } from 'next'

export function generateStaticParams() {
  return linguiConfig.locales.map((locale) => ({ lang: locale }))
}

export const metadata: Metadata = {
  metadataBase: new URL('https://starter-next-app-two.vercel.app/'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  appleWebApp: {
    title: 'Starter Next App',
  },
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '96x96',
      url: '/favicon-96x96.png',
    },
    {
      rel: 'icon',
      type: 'image/svg+xml',
      url: '/favicon.svg',
    },
    {
      rel: 'shortcut icon',
      url: '/favicon.ico',
    },
    {
      rel: 'app-touch-icon',
      sizes: '180x180',
      url: '/apple-touch-icon.png',
    },
  ],
  openGraph: {
    title: 'Starter Next App',
    description: 'Generated by create next app',
    siteName: 'Starter Next App',
    images: [{ url: '/og.png' }],
  },
}

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ lang: SupportedLocale }>
}) {
  const { lang } = await params

  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  )
}
